name    'noma4i/windows_autologon'
version '0.0.1'
author 'noma4i'
license 'MIT'
summary 'Set a Windows Computer for automatic logon.'
project_page 'https://github.com/noma4i/puppet-windows_autologon
'
dependency    'joshcooper/powershell (>=0.0.5)'